-- MySQL Script generated by MySQL Workbench
-- Thu Jan 22 02:13:57 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema hackathon_108
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hackathon_108` ;

-- -----------------------------------------------------
-- Schema hackathon_108
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hackathon_108` DEFAULT CHARACTER SET utf8mb4 ;
SHOW WARNINGS;
USE `hackathon_108` ;

-- -----------------------------------------------------
-- Table `ambulance_location_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambulance_location_logs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ambulance_location_logs` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ambulance_id` BIGINT(20) NOT NULL,
  `emergency_id` BIGINT(20) NULL DEFAULT NULL,
  `lat` DOUBLE NOT NULL,
  `lng` DOUBLE NOT NULL,
  `ts` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `ambulance_location_logs_ibfk_1`
    FOREIGN KEY (`ambulance_id`)
    REFERENCES `ambulances` (`id`),
  CONSTRAINT `ambulance_location_logs_ibfk_2`
    FOREIGN KEY (`emergency_id`)
    REFERENCES `emergencies` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE INDEX `idx_location_logs_ambulance_time` ON `ambulance_location_logs` (`ambulance_id` ASC, `ts` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_ambulance_emergency` ON `ambulance_location_logs` (`ambulance_id` ASC, `emergency_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_emergency_ts` ON `ambulance_location_logs` (`emergency_id` ASC, `ts` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ambulances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ambulances` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ambulances` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `driver_name` VARCHAR(255) NULL DEFAULT NULL,
  `driver_phone` VARCHAR(255) NULL DEFAULT NULL,
  `status` ENUM('AVAILABLE', 'BUSY') NOT NULL,
  `last_lat` DOUBLE NULL DEFAULT NULL,
  `last_lng` DOUBLE NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `version` BIGINT(20) NOT NULL,
  `ambulance_type` ENUM('GOVERNMENT', 'PRIVATE') NOT NULL DEFAULT 'GOVERNMENT' COMMENT 'Fleet classification for dispatch matching',
  `base_fare` DOUBLE NULL DEFAULT NULL,
  `per_km_rate` DOUBLE NULL DEFAULT NULL,
  `driver` VARCHAR(255) NULL DEFAULT NULL,
  `license_plate` VARCHAR(22) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 305
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE UNIQUE INDEX `code` ON `ambulances` (`code` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `license_plate` ON `ambulances` (`license_plate` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_ambulance_status` ON `ambulances` (`status` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_ambulance_type` ON `ambulances` (`ambulance_type` ASC, `status` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `audit_events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `audit_events` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `audit_events` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `aggregate_id` BIGINT(20) NOT NULL,
  `aggregate_type` VARCHAR(255) NOT NULL,
  `event_type` VARCHAR(255) NOT NULL,
  `message` VARCHAR(2000) NOT NULL,
  `occurred_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE INDEX `idx_audit_type` ON `audit_events` (`event_type` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_audit_time` ON `audit_events` (`occurred_at` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `domain_events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domain_events` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `domain_events` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `aggregate_id` BIGINT(20) NULL DEFAULT NULL,
  `aggregate_type` VARCHAR(255) NOT NULL,
  `event_type` VARCHAR(255) NOT NULL,
  `message` VARCHAR(1000) NOT NULL,
  `occurred_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `driver_documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `driver_documents` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `driver_documents` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `document_urls` TEXT NULL DEFAULT NULL,
  `id_proof_number` VARCHAR(255) NOT NULL,
  `license_number` VARCHAR(255) NOT NULL,
  `submitted_at` DATETIME(6) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `document_url` TEXT NULL DEFAULT NULL,
  `driver_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKgy9d1je5hg1sdjjnrov81bqyc`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 503
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE UNIQUE INDEX `UK_93wlfu0f74cfocpv0uxlbcubd` ON `driver_documents` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `driver_sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `driver_sessions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `driver_sessions` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `driver_id` BIGINT(20) NOT NULL,
  `ambulance_id` BIGINT(20) NOT NULL,
  `status` ENUM('ONLINE', 'ON_TRIP', 'OFFLINE') NOT NULL,
  `session_start_time` DATETIME(6) NOT NULL,
  `session_end_time` DATETIME(6) NULL DEFAULT NULL,
  `current_lat` DOUBLE NULL DEFAULT NULL,
  `current_lng` DOUBLE NULL DEFAULT NULL,
  `location_updated_at` DATETIME(6) NULL DEFAULT NULL,
  `emergencies_handled` INT(11) NOT NULL DEFAULT 0,
  `version` BIGINT(20) NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `last_heartbeat` DATETIME(6) NULL DEFAULT NULL COMMENT 'Last GPS heartbeat received from driver app. Updated every 3-5 seconds.',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_driver_session_ambulance`
    FOREIGN KEY (`ambulance_id`)
    REFERENCES `ambulances` (`id`),
  CONSTRAINT `fk_driver_session_driver`
    FOREIGN KEY (`driver_id`)
    REFERENCES `users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 408
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `uk_active_driver` ON `driver_sessions` (`driver_id` ASC, `status` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `uk_active_ambulance` ON `driver_sessions` (`ambulance_id` ASC, `status` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_driver_status` ON `driver_sessions` (`driver_id` ASC, `status` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_ambulance_status` ON `driver_sessions` (`ambulance_id` ASC, `status` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_status_started` ON `driver_sessions` (`status` ASC, `session_start_time` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_driver_session_heartbeat` ON `driver_sessions` (`status` ASC, `last_heartbeat` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `emergencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emergencies` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `emergencies` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NULL DEFAULT NULL COMMENT 'User who created emergency (for tracking authorization)',
  `type` VARCHAR(255) NULL DEFAULT NULL,
  `severity` VARCHAR(255) NULL DEFAULT NULL,
  `lat` DOUBLE NOT NULL,
  `lng` DOUBLE NOT NULL,
  `hospital_latitude` DOUBLE NULL DEFAULT NULL COMMENT 'Target hospital latitude coordinate',
  `hospital_longitude` DOUBLE NULL DEFAULT NULL COMMENT 'Target hospital longitude coordinate',
  `distance_to_hospital` DOUBLE NULL DEFAULT NULL COMMENT 'Distance in meters when completion was attempted',
  `status` ENUM('CREATED', 'IN_PROGRESS', 'DISPATCHED', 'AT_PATIENT', 'TO_HOSPITAL', 'COMPLETED', 'UNASSIGNED') NOT NULL,
  `assigned_ambulance_id` BIGINT(20) NULL DEFAULT NULL,
  `ai_first_aid` TEXT NULL DEFAULT NULL,
  `ai_doctor_summary` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `confirmation_deadline` DATETIME NULL DEFAULT NULL COMMENT 'User must confirm within 100 seconds after creation',
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  `status_updated_at` DATETIME(6) NULL DEFAULT NULL,
  `completed_at` DATETIME NULL DEFAULT NULL COMMENT 'Timestamp when emergency was marked COMPLETED',
  `version` BIGINT(20) NOT NULL,
  `source_type` ENUM('GOVERNMENT', 'PRIVATE') NOT NULL DEFAULT 'GOVERNMENT' COMMENT 'GOVERNMENT=free service, PRIVATE=paid service',
  `payment_status` ENUM('NOT_REQUIRED', 'PENDING', 'AUTHORIZED', 'PAID', 'FAILED', 'REFUNDED') NOT NULL DEFAULT 'NOT_REQUIRED' COMMENT 'Payment tracking for PRIVATE emergencies',
  `fare_amount` DOUBLE NULL DEFAULT NULL,
  `payment_intent_id` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Razorpay/Stripe payment intent ID for tracking',
  `is_suspect_cancellation` TINYINT(1) NULL DEFAULT 0 COMMENT 'True if cancelled after confirmation deadline',
  PRIMARY KEY (`id`),
  CONSTRAINT `emergencies_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`),
  CONSTRAINT `emergencies_ibfk_2`
    FOREIGN KEY (`assigned_ambulance_id`)
    REFERENCES `ambulances` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE INDEX `assigned_ambulance_id` ON `emergencies` (`assigned_ambulance_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_emergencies_status` ON `emergencies` (`status` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_emergency_user_id` ON `emergencies` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_emergency_status_created` ON `emergencies` (`status` ASC, `created_at` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_emergency_payment` ON `emergencies` (`source_type` ASC, `payment_status` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_emergencies_confirmation_deadline` ON `emergencies` (`confirmation_deadline` ASC, `status` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_emergencies_pending_dispatch` ON `emergencies` (`status` ASC, `created_at` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `emergency_assignments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emergency_assignments` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `emergency_assignments` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `assigned_at` DATETIME NOT NULL,
  `timeout_at` DATETIME NULL DEFAULT NULL COMMENT 'Driver must respond before this time',
  `response_time_seconds` INT(11) NULL DEFAULT NULL COMMENT 'Time taken by driver to respond (accept/reject)',
  `status` ENUM('ASSIGNED', 'ACCEPTED', 'REJECTED', 'TIMEOUT', 'COMPLETED', 'CANCELLED') NOT NULL,
  `ambulance_id` BIGINT(20) NOT NULL,
  `driver_id` BIGINT(20) NULL DEFAULT NULL,
  `emergency_id` BIGINT(20) NOT NULL,
  `response_deadline` DATETIME NULL DEFAULT NULL,
  `accepted_at` TIMESTAMP NULL DEFAULT NULL,
  `rejected_at` TIMESTAMP NULL DEFAULT NULL,
  `completed_at` TIMESTAMP NULL DEFAULT NULL,
  `cancelled_at` DATETIME NULL DEFAULT NULL COMMENT 'When assignment was cancelled (system timeout or emergency cancelled)',
  `cancellation_reason` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Reason for cancellation: DRIVER_TIMEOUT, EMERGENCY_CANCELLED, etc.',
  `active_emergency_id` BIGINT(20) GENERATED ALWAYS AS (case when `status` in ('ASSIGNED','ACCEPTED') then `emergency_id` else NULL end) STORED,
  `version` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK3vqpou20w6txlww6tvdmra0h1`
    FOREIGN KEY (`emergency_id`)
    REFERENCES `emergencies` (`id`),
  CONSTRAINT `FKjhpwulsfrd9a7mlsw0f4k2riq`
    FOREIGN KEY (`ambulance_id`)
    REFERENCES `ambulances` (`id`),
  CONSTRAINT `fk_assignment_driver`
    FOREIGN KEY (`driver_id`)
    REFERENCES `users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE UNIQUE INDEX `uq_active_assignment_per_emergency` ON `emergency_assignments` (`active_emergency_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FKjhpwulsfrd9a7mlsw0f4k2riq` ON `emergency_assignments` (`ambulance_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_assignments_emergency` ON `emergency_assignments` (`emergency_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_assignments_status` ON `emergency_assignments` (`status` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_assignments_deadline` ON `emergency_assignments` (`response_deadline` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_driver_id` ON `emergency_assignments` (`driver_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_assignment_driver` ON `emergency_assignments` (`driver_id` ASC, `status` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_assignments_active` ON `emergency_assignments` (`emergency_id` ASC, `status` ASC, `assigned_at` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `emergency_contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emergency_contacts` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `emergency_contacts` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(15) NULL DEFAULT NULL,
  `relation` VARCHAR(50) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  CONSTRAINT `emergency_contacts_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 603
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE INDEX `user_id` ON `emergency_contacts` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `otp_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otp_codes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `otp_codes` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `expires_at` DATETIME(6) NULL DEFAULT NULL,
  `phone_or_email` VARCHAR(255) NULL DEFAULT NULL,
  `used` BIT(1) NOT NULL,
  `identifier` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE INDEX `idx_identifier_used` ON `otp_codes` (`identifier` ASC, `used` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_phone_email` ON `otp_codes` (`phone_or_email` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `users` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `language` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `email` VARCHAR(100) NOT NULL,
  `role` ENUM('PUBLIC', 'DRIVER', 'ADMIN') NOT NULL,
  `active` BIT(1) NOT NULL,
  `blocked` BIT(1) NOT NULL,
  `suspect_count` INT(11) NULL DEFAULT 0 COMMENT 'Number of times user cancelled after confirmation deadline',
  `last_suspect_at` DATETIME NULL DEFAULT NULL COMMENT 'Timestamp of most recent suspect cancellation',
  `otp` VARCHAR(6) NULL DEFAULT NULL COMMENT 'Current OTP for authentication',
  `otp_generated_at` DATETIME(6) NULL DEFAULT NULL COMMENT 'When OTP was generated',
  `admin_passkey` VARCHAR(8) NULL DEFAULT NULL COMMENT '8-digit passkey for admin users',
  `address` TEXT NULL DEFAULT NULL COMMENT 'User address',
  `document_url` VARCHAR(500) NULL DEFAULT NULL COMMENT 'Driver verification document URL',
  `is_profile_complete` TINYINT(1) NULL DEFAULT 0 COMMENT 'Whether user completed profile setup',
  `driver_verification_status` ENUM('NOT_REQUIRED', 'PENDING', 'VERIFIED', 'REJECTED') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 206
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE UNIQUE INDEX `uq_users_email` ON `users` (`email` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `phone` ON `users` (`phone` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_users_otp` ON `users` (`phone` ASC, `otp` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_users_verification_pending` ON `users` (`role` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `idx_users_suspect_count` ON `users` (`suspect_count` ASC, `last_suspect_at` ASC) VISIBLE;

SHOW WARNINGS;
USE `hackathon_108`;

DELIMITER $$

USE `hackathon_108`$$
DROP TRIGGER IF EXISTS `trg_assignment_time_guard_insert` $$
SHOW WARNINGS$$
USE `hackathon_108`$$
CREATE
DEFINER=`emergency_user`@`localhost`
TRIGGER `hackathon_108`.`trg_assignment_time_guard_insert`
BEFORE INSERT ON `hackathon_108`.`emergency_assignments`
FOR EACH ROW
BEGIN
    IF NEW.accepted_at IS NOT NULL AND NEW.accepted_at < NEW.assigned_at THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'accepted_at cannot be before assigned_at';
    END IF;

    IF NEW.completed_at IS NOT NULL THEN
        IF NEW.accepted_at IS NULL THEN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'completed_at requires accepted_at';
        END IF;

        IF NEW.completed_at < NEW.accepted_at THEN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'completed_at cannot be before accepted_at';
        END IF;
    END IF;
END$$

SHOW WARNINGS$$

USE `hackathon_108`$$
DROP TRIGGER IF EXISTS `trg_assignment_time_guard_update` $$
SHOW WARNINGS$$
USE `hackathon_108`$$
CREATE
DEFINER=`emergency_user`@`localhost`
TRIGGER `hackathon_108`.`trg_assignment_time_guard_update`
BEFORE UPDATE ON `hackathon_108`.`emergency_assignments`
FOR EACH ROW
BEGIN
    IF NEW.accepted_at IS NOT NULL AND NEW.accepted_at < NEW.assigned_at THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'accepted_at cannot be before assigned_at';
    END IF;

    IF NEW.completed_at IS NOT NULL THEN
        IF NEW.accepted_at IS NULL THEN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'completed_at requires accepted_at';
        END IF;

        IF NEW.completed_at < NEW.accepted_at THEN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'completed_at cannot be before accepted_at';
        END IF;
    END IF;
END$$

SHOW WARNINGS$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
